### ISSUE TITLE
can't compile anymore

### ISSUE THREAD

**Issue by rofl0r** [sabotage-linux/gettext-tiny#31]
```
cc  -static -o msgfmt src/msgfmt.o src/poparser.o src/StringEscape.o -liconv
/bin/ld: cannot find -liconv
```

**Comment by xhebox** [comment]
Sorry, my bad, i should have tested it under linux. But i still think we better handle iconv, what about:

```
LDFLAGS=$(pkg-config --silence-errors --libs iconv)
```

Both tested under win+msys2+pkg-config and linux+pkgconf. When we need iconv, there will be a flag; when there's no iconv(musl), it wont print errors so that there're no redundant strings in LDFLAGS.

And maybe we could set a new variable `PKG_CONFIG` to let users choose their own `pkgconf` command.

**Comment by rofl0r** [comment]
what's the error you getting when compiling under mingw without -liconv ?
i'm still trying to understand the issue.

in the meantime, however we fix/add support for mingw, see my PR, it reverts the broken commit and fixes the order of LDFLAGS.

**Comment by xhebox** [comment]
Here it is:

```
cc  -static -o msgmerge src/msgmerge.o src/poparser.o src/StringEscape.o
src/poparser.o:poparser.c:(.text+0x541): undefined reference to `libiconv_open'
src/poparser.o:poparser.c:(.text+0x5d1): undefined reference to `libiconv_open'
src/poparser.o:poparser.c:(.text+0x5fa): undefined reference to `libiconv'
```

I guess, this will happen on other platforms with separated iconv.

**Comment by rofl0r** [comment]
i don't know, but iconv_open() and friends are POSIX standard (see man 3p posix_open), and even on GLIBC do not require a separate libiconv:
here's output from ubuntu 16.04
```
$ gcc test.c -liconv
test.c: In function ‘main’:
test.c:4:9: warning: return makes integer from pointer without a cast [-Wint-conversion]
  return iconv_open("", "");
         ^
/usr/bin/ld: cannot find -liconv
collect2: error: ld returned 1 exit status
```
i'll apply my PR to restore master to a non-broken state, after that we can discuss how to add support for mingw.
