### ISSUE TITLE
Static linking with iconv

### ISSUE THREAD

**Issue by vkochan** [sabotage-linux/gettext-tiny#37]
Is it must to enforce static linking with iconv ? What about to remove '-static' linking or to add
an option which controls this ( I can try to do this) ?

Thanks!

**Comment by xhebox** [comment]
IMO, it makes sense when iconv is deleted by mistakes. But it's made by @rofl0r, not me anyway, let's see what argument he holds...

By the way, would you even mind it, for disk size, or what? On musl, you dont even have a libiconv...

**Comment by xhebox** [comment]
I see.

But let me clarify. gettext-tiny does not provide libintl. the libintl stub is used to pass configure... gettet-tiny only do one thing: compiling .po files successfully.

If you want to find stub for libintl, then tiny may be the wrong choice. Since, for something like fcitx, which actually use functions from libintl, tiny will be useless to it.

And, this issue should not be closed for now. I'm not against with adding a new option, instead, i think it's nice.

**Comment by rofl0r** [comment]
actually musl has the libintl built in. thus we have options to use an external libintl.

> gettet-tiny only do one thing: compiling .po files smoothly(and related works).

not only that, it allows to get past configure-check's of software that wants to see GNU's gettext installed.

@vkochan your request is totally legit, and i shouldn't have hardcoded my personal preferences into the Makefile to begin with.
i'd love to see gettext-tiny packaged buildroot. thanks for considering it!
