### ISSUE TITLE
msgfmt segfaults building git 2.19.1

### ISSUE THREAD

**Issue by rofl0r** [sabotage-linux/gettext-tiny#39]
to reproduce:
```
msgfmt --check --statistics -o ru.mo po/ru.po
```

resulting in:
```
Program received signal SIGSEGV, Segmentation fault.
0x000000000040273c in process (in=0x605340, out=0x7ffff7ffb020)
    at src/msgfmt.c:471
471                     d.strlist[i].trans->off += d.off + d.len[pe_msgid] + d.len[pe_plural] + d.len[pe_ctxt];
(gdb) p i
$1 = 1
(gdb) p d.strlist[i]
$2 = {str = {len = 0, off = 53980}, trans = 0x0}
(gdb) p d.strlist[i-1]
$3 = {str = {len = 0, off = 53980}, trans = 0x619480}
```
the trans pointer of the second item is NULL. interestingly the 2nd item seems identical to the first apart from the trans pointer. i guess it's from the empty `msgid ""` string right at the start of the file.

@xhebox do you have time to look into this ?

**Comment by xhebox** [comment]
@rofl0r I can take a try, but i will let you know if i can not complete it under this broken system. I just escape from the busy and hard time as a freshman. And i'm currently busy on  fixing my broken toolchain and broken distribution.

**Comment by xhebox** [comment]
@rofl0r  here's why:

```
msgid "ordered %u objects, expected %<PRIu32>"
msgstr ""
```

Here, a sysdep msgid, but an empty msgstr, resulting in a mismatched num of msgid/msgstr(`msgid - msgstr == 1`).  And my dirty hack to drop empty msgstr translation makes the num equal improperly, so `abort()` is avoided, and segfault came naturally.

We really need a good logic in `process_line_callback`, so that we can drop an invalid translation anytime we want. One has came up to my mind: we could use a struct to record the whole `ctxt/id/plural/str` process when `collect_size/copy_string`, rather than playing with just a `priv_type` that could only tell me what previous statement is...

This actually reminds me that the `poparser` is also a bit tricky... These issues occurred over and over again on gettext-tiny. Not a surprise, we can not use hacks to meet the needs anymore. So i propose a new poparser, which:

1. parses po files into blocks. Each block corresponds to a msgid, a possible msgctxt/msgid_plural, and possibly multiple msgstr, and some recognizable comments(start with `#:, #,`) generated by xgettext. Blank lines and normal comments are ignored.

2. is not using action_tbl in `feed_line()` and not calling the cb_func everytime a newline is fed.  `action_tbl`is just a 2d array, it can just care about two states. But we have to care about at least four states(ctxt/id/plural/str). We need to care about the whole block, or we need a bigger state machine in another word.

We should just parse the new lines, check if the block is terminated, and leave the all work to the callback function once a new block is parsed.

**Comment by rofl0r** [comment]
> msgid "ordered %u objects, expected %<PRIu32>"
> msgstr ""

what does gnu gettext do with this one ?

**Comment by xhebox** [comment]
Drop it. Empty msgstr is ignored by default. -C will trigger an error, since X/Open format strictly not allow the existence of emty msgstr. But to be honest, empty msgstr makes translation more convenient for translators.

**Comment by rofl0r** [comment]
ok. do you have time to work on your suggested poparser modifications ? i suspect it should not be too much work...

**Comment by xhebox** [comment]
I have. No more than 1k loc, i guess. One week should be OK. Since i have other things in the meantime.

**Comment by rofl0r** [comment]
1000 lines ? i hope not :)
joking aside, that's really good news, thanks!

**Comment by xhebox** [comment]
@rofl0r i've opened a new branch. actually the newpoparser managed to reduce some codes... msgfmt greatly reduced by 243 while poparser.c increased by 152.

let's go back to the main topic. i only completed the work of poparser and msgfmt this weekend. msgmerge, though, is quite simple to rewrite, i have to leave it for the next weekend(or earlier). you could also try to rewrite, since msgmerge is just doing copy. you could test the new msgfmt freely. bug is welcome.

besides, the new parser is completely capable of parsing po header and flags in comments. i only parse `charset, nplurals, fuzzy` as the old one, but we could now extend those with ease.

**Comment by rofl0r** [comment]
great job. i left a number of comments on your commits. i think you oversimplified the sysdep replacement code, and the version you provide is unfit for anything but the most simple cases. imo it should be possible to fit in the previous code, which i tested rigorously back when i wrote it. anyway, i'm waiting for your comments...

**Comment by rofl0r** [comment]
for the record, this was the commit adding the sysdep expansion: https://github.com/sabotage-linux/gettext-tiny/commit/438a47cf6da6dba04b04fee983c247cc13430b6c

**Comment by rofl0r** [comment]
> but attention, we dont need to do mulplication for duplicated %<xxx>, e.g. no case(%<PRIu32>) x case(%<PRIu32>). because, how could there be a platform where PRIu32 could be u and lu at the same time?

our produced .mo files need to be **portable across systems**.
that means it's possible to create a .mo file on x86_64, but use it on i386.
therefore an input string containing e.g. PRIu64, will depending on the libc of the user, generate either "lu" or "llu", so our generated .mo file need to create one msgid string with "lu" and another one with "llu" to have all bases covered. if there's more than sysdep string, this leads to the combinatorial explosion which my existing code covers correctly.

**Comment by xhebox** [comment]
@rofl0r the new branch, whatever, passed my test. i'd like to hear a reply from you.

**Comment by rofl0r** [comment]
great, thank you! i've asked @selkfoster to test your branch, maybe @awilfox could have a look too ? as you know sabotage itself does not use translations, so it's not really suited for testing (almost all packages are using --disable-nls).

**Comment by selkfoster** [comment]
I will test the new parser branch, this take too much time, because it implies to rebuild all the packages.  I will be able to test probably this weekend, I will let you know guys ...

**Comment by xhebox** [comment]
@rofl0r this seems obvious. i use strstr to search, which will match PRIu32 first if it's there... i will give a solution after class. use strchr first, and try to match one of three sysdep strings. thx for your efforts :).

**Comment by selkfoster** [comment]
True.  This build (git) now works fine against the newpoparser.  :-)

**Comment by xhebox** [comment]
https://github.com/sabotage-linux/gettext-tiny/issues/40#issuecomment-466737398, closed.
