### ISSUE TITLE
xgettext fails to parse arguments

### ISSUE THREAD

**Issue by giuliobenetti** [sabotage-linux/gettext-tiny#42]
Msgmerge exits with:
fopen: No such file or directory

when called with these flags:
msgmerge -U --no-wrap --no-location --backup=none -q -N po/lt_LT.po po/vnsiserver.pot

I've tried setting first argument of set_file() in the case of .pot files that should make fopen using "w" but what I obtain is an output to stdout and a zero length output file.
Can you fix it please?

It doesn't support update functionality too, can you implement it?

Thanks in advance

**Comment by vkochan** [comment]
Hi All!

Just FYI,

the issue was reported by buildroot's autobuild system and logs can be found here:

http://autobuild.buildroot.org/results/0c230e49b6e9bf27163f751e6912ee85c6eb62e3/build-end.log

Thank you!

**Comment by xhebox** [comment]
OK... First, this is not an issue of msgmerge. msgmerge wont generate .pot but xgettext.

Our msgmerge/xgettext is mostly a stub than an implementation. Now the build should be fixed by the latest commit.

As for the `update`, there're two parts to do:

1. xgettext: need to write partial source code parser to extract new strings into .pot
2. msgmerge: merge .pot and .po, need to parse comments

Because now gettext-tiny use a whole new parser, it's not so hard to implement msgmerge. You could open a new issue for msgmerge, and close this issue after checking the latest commit.

But it's not our goal to provide full tools(xgettext/etc.) for developers/translators. Our goal is to provide a lightweight alternative to build, not whole automatic tool set.

You may ask the author to release a pre-processed tarball, which has pre-built .pot and updated .po. That's what most software do.

**Comment by giuliobenetti** [comment]
Thank you for explaining me and for the code, I give it a try.

**Comment by giuliobenetti** [comment]
Now it works, thank you.
