### ISSUE TITLE
Any updates on a new release?

### ISSUE THREAD

**Issue by firasuke** [sabotage-linux/gettext-tiny#57]
Hey there, thanks for your time and effort.

I was wondering if there are any plans for a new release anytime soon?

**Comment by xhebox** [comment]
Glad to see that you like our work. :)

There is indeed a need for a new release. I have thought about it months ago.

While I am the main contributor/developer of this project, I am not actively interacted with the owner of this repo: @rofl0r, due to my half-broken linux distro(now firefox is my only GUI application since I switched to pure wayland).

I will try to bring back irssi; and have a discussion with rofl0r on IRC.

**Comment by firasuke** [comment]
I see.

Keep up the great work!

**Comment by rofl0r** [comment]
@xhebox are you ok with tagging current master as a new release ?
if that's ok with you i can upload a release the next couple days.

**Comment by xhebox** [comment]
@rofl0r it is ok. :)

**Comment by rofl0r** [comment]
thanks, done: https://github.com/sabotage-linux/gettext-tiny/releases/tag/v0.3.2

**Comment by firasuke** [comment]
Thanks for the new release!
